# Generated by Django 4.0.4 on 2022-07-17 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0002_alter_card_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_to_do',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=777, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_accepted_task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто взял таск'),
        ),
    ]
