# Generated by Django 4.0.4 on 2022-07-17 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0003_card_date_to_do_alter_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_to_do',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 18, 4, 49, 951157, tzinfo=utc), help_text='format=2022-07-17 17:36:29'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_cards', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskmanager.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
